name: Generate 3D Contribution Graph

on:
  schedule:
    - cron: "0 */6 * * *"   # har 6 ghante me refresh
  workflow_dispatch: {}

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - uses: yoshi389111/github-profile-3d-contrib@0.9.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          USERNAME: nilesh24rit

      - name: Commit & push generated files
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add -f profile-3d-contrib/*.svg
          git commit -m "generate 3d contribution graph" || echo "no changes"
          git push origin output || (git checkout -b output && git push -u origin output)
